include "syntax.dfy"
include "Utils_SlimState.dfy"
include "utils/collections.dfy"
include "Lemmas.dfy"
include "Properties_utils.dfy"
include "Lemmas_Ops.dfy"
include "BuildCAS/BuildCAS.dfy"
include "Lemmas_SubjActivate_ReachableTDsStates.dfy"
include "Lemmas_SubjActivate_Ops.dfy"
include "Lemmas_SubjDeactivate_ReachableTDsStates.dfy"
include "Lemmas_SubjDeactivate_Ops.dfy"
include "SecurityProperties_Ops.dfy"
include "Model.dfy"
include "Lemmas_Ops_DrvDevRead.dfy"
include "SecurityProperties.dfy"

